# Generated by Django 3.1.1 on 2020-10-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('setting', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1)),
                ('leveling', models.CharField(choices=[('L', 'Leveling'), ('S', 'Standby')], default='L', max_length=1)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
