# Generated by Django 3.1.1 on 2020-10-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='color',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=20),
        ),
        migrations.AlterField(
            model_name='talent',
            name='leveling',
            field=models.CharField(choices=[('Leveling', 'Leveling'), ('Standby', 'Standby')], default='Leveling', max_length=20),
        ),
        migrations.AlterField(
            model_name='talent',
            name='setting',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
