# Generated by Django 3.1.1 on 2020-10-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201011_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='color',
            field=models.CharField(choices=[('text-white bg-primary', 'Blue'), ('text-white bg-secondary', 'Grey'), ('text-white bg-success', 'Green'), ('text-white bg-danger', 'Red'), ('text-white bg-warning', 'Yellow'), ('text-white bg-info', 'Aqua'), ('bg-light', 'White'), ('text-white bg-dark', 'Dark Grey')], default='text-white bg-primary', max_length=30),
        ),
    ]
