# Generated by Django 3.1.1 on 2020-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201012_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='leveling',
            field=models.CharField(choices=[('Active', 'Active'), ('Standby', 'Standby'), ('0 Exp', '0 Exp')], default='Active', max_length=20),
        ),
    ]
