# Generated by Django 3.1.1 on 2020-10-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_learn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='user',
        ),
    ]
