# Generated by Django 3.1.1 on 2020-10-13 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_learn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
