# Generated by Django 3.1.1 on 2020-10-13 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_auto_20201013_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='leveling',
            field=models.CharField(choices=[('Active', 'Active'), ('Standby', 'Standby')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Standby', 'Standby')], default='Active', max_length=20)),
                ('image', models.CharField(max_length=1000)),
                ('color', models.CharField(choices=[('text-white bg-primary', 'Blue'), ('text-white bg-secondary', 'Grey'), ('text-white bg-success', 'Green'), ('text-white bg-danger', 'Red'), ('text-white bg-warning', 'Yellow'), ('text-white bg-info', 'Aqua'), ('text-white bg-dark', 'Dark Grey')], default='text-white bg-primary', max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
