# Generated by Django 3.1.1 on 2020-10-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201013_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
